apiVersion: v1
kind: Pod
metadata:
  name: sql-pod
  labels:
    name: catvision-sql
spec:
  containers:
  - name: catvision-sql
    image: catvision/sql:1.0
    resources:
      limits:
        memory: "1G"
        cpu: "500m"
    ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-sql
spec:
  ports:
  - name: db-port
    protocol: "TCP"
    port: 3306
    targetPort: 3306
  selector:
    app: mysql