apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
     matchLabels:
       app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mysqlinst
      securityContext:
        fsGroup: 10001
      containers:
      - name: mysql
        image: mysql:latest
        resources:
          limits:
            memory: "1G"
            cpu: "500m"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: catvision
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_USER
          value: catvision
        - name: MYSQL_PASSWORD
          value: Catvision_1234
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-deployment
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer