apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: catvision-api
  name: catvision-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy: {}
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: catvision:0.0.1-SNAPSHOT
        name: catvision
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-demo
  name: api-demo
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-demo
  type: ClusterIP
status:
  loadBalancer: {}